// Shared generator for data/geojsonManifest.ts.
//
// Scans ALL GeoJSON under public/data (shapefile conversions, CSV→point layers,
// anything else) and writes a single manifest keyed by runtime URL. Both
// scripts/convert-shapefiles.ts and scripts/extract-table-points.ts call this so
// neither clobbers the other's entries — the manifest always reflects what is
// actually on disk.

import fs from 'fs';
import path from 'path';

const walk = (dir: string, acc: string[] = []): string[] => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, acc);
    else if (entry.name.toLowerCase().endsWith('.geojson')) acc.push(full);
  }
  return acc;
};

export interface GeojsonManifestEntry {
  bytes: number;
  features: number;
}

/** Rebuild data/geojsonManifest.ts from disk. Returns the number of entries. */
export const rebuildGeojsonManifest = (root: string): number => {
  const publicDir = path.resolve(root, 'public');
  const dataDir = path.resolve(publicDir, 'data');
  const manifestPath = path.resolve(root, 'data/geojsonManifest.ts');

  const files = fs.existsSync(dataDir) ? walk(dataDir) : [];
  const entries: Record<string, GeojsonManifestEntry> = {};
  for (const file of files) {
    const raw = fs.readFileSync(file, 'utf8');
    let features = 0;
    try {
      const gj = JSON.parse(raw);
      features = Array.isArray(gj.features) ? gj.features.length : 0;
    } catch {
      continue; // not valid JSON — skip rather than list a broken file
    }
    const url = '/' + path.relative(publicDir, file).split(path.sep).join('/');
    entries[url] = { bytes: Buffer.byteLength(raw, 'utf8'), features };
  }

  const keys = Object.keys(entries).sort();
  const body = keys
    .map((k) => `  ${JSON.stringify(k)}: { bytes: ${entries[k].bytes}, features: ${entries[k].features} },`)
    .join('\n');
  const ts = `// AUTO-GENERATED by scripts/lib/geojsonManifest.ts — do not edit by hand.
// Lists browser-renderable GeoJSON files under /public/data (shapefile
// conversions and CSV→point layers). The capability check
// (utils/previewCapability.ts) treats a geojsonUrl present here as renderable;
// MapViewer / the catalog fetch the file at runtime.

export interface GeojsonManifestEntry {
  /** On-disk size of the generated .geojson (bytes). */
  bytes: number;
  /** Feature count. */
  features: number;
}

export const GEOJSON_MANIFEST: Record<string, GeojsonManifestEntry> = {
${body}
};
`;
  fs.writeFileSync(manifestPath, ts, 'utf8');
  return keys.length;
};
