// AUTO-GENERATED by scripts/convert-shapefiles.ts — do not edit by hand.
// Lists browser-renderable GeoJSON files produced from source shapefiles. The
// capability check (utils/previewCapability.ts) treats a geojsonUrl present here
// as renderable; MapViewer / the catalog fetch the file at runtime.

export interface GeojsonManifestEntry {
  /** On-disk size of the generated .geojson (bytes). */
  bytes: number;
  /** Feature count after conversion. */
  features: number;
  /** Visvalingam retention used to fit the size budget. */
  simplify: string;
}

export const GEOJSON_MANIFEST: Record<string, GeojsonManifestEntry> = {
  "/data/administrative-boundaries/all-ndcs.geojson": { bytes: 461740, features: 114, simplify: "20%" },
  "/data/administrative-boundaries/amerindian-areas.geojson": { bytes: 673591, features: 110, simplify: "20%" },
  "/data/administrative-boundaries/anna-regina-boundary.geojson": { bytes: 747, features: 1, simplify: "20%" },
  "/data/administrative-boundaries/bartica-municipality.geojson": { bytes: 4687, features: 8, simplify: "20%" },
  "/data/administrative-boundaries/corriverton-constituencies.geojson": { bytes: 4542, features: 7, simplify: "20%" },
  "/data/administrative-boundaries/georgetown-constituencies.geojson": { bytes: 7520, features: 15, simplify: "20%" },
  "/data/administrative-boundaries/guyana-exclusive-economic-zone.geojson": { bytes: 3147, features: 1, simplify: "20%" },
  "/data/administrative-boundaries/guyana-national-boundary.geojson": { bytes: 49464, features: 1, simplify: "20%" },
  "/data/administrative-boundaries/lethem-constituencies.geojson": { bytes: 8509, features: 6, simplify: "20%" },
  "/data/administrative-boundaries/linden-town-constituencies.geojson": { bytes: 10348, features: 8, simplify: "20%" },
  "/data/administrative-boundaries/local-government-areas.geojson": { bytes: 1424185, features: 224, simplify: "12%" },
  "/data/administrative-boundaries/mabaruma-constituencies.geojson": { bytes: 5525, features: 6, simplify: "20%" },
  "/data/administrative-boundaries/mahdia-boundary.geojson": { bytes: 901, features: 1, simplify: "20%" },
  "/data/administrative-boundaries/region-1-boundary.geojson": { bytes: 17667, features: 1, simplify: "20%" },
  "/data/administrative-boundaries/region-1-ndcs.geojson": { bytes: 74322, features: 5, simplify: "20%" },
  "/data/administrative-boundaries/region-10-ndcs.geojson": { bytes: 10356, features: 8, simplify: "20%" },
  "/data/administrative-boundaries/region-2-ndcs.geojson": { bytes: 13914, features: 7, simplify: "20%" },
  "/data/administrative-boundaries/region-3-ndcs.geojson": { bytes: 67707, features: 17, simplify: "20%" },
  "/data/administrative-boundaries/region-4-ndcs.geojson": { bytes: 33241, features: 19, simplify: "20%" },
  "/data/administrative-boundaries/region-5-ndcs.geojson": { bytes: 108778, features: 13, simplify: "20%" },
  "/data/administrative-boundaries/region-5-villages.geojson": { bytes: 120052, features: 202, simplify: "20%" },
  "/data/administrative-boundaries/region-6-ndcs.geojson": { bytes: 23036, features: 21, simplify: "20%" },
  "/data/administrative-boundaries/region-7-ndcs.geojson": { bytes: 46935, features: 8, simplify: "20%" },
  "/data/administrative-boundaries/region-8-ndcs.geojson": { bytes: 13262, features: 8, simplify: "20%" },
  "/data/administrative-boundaries/region-9-boundary.geojson": { bytes: 9929, features: 1, simplify: "20%" },
  "/data/administrative-boundaries/region-9-ndcs.geojson": { bytes: 19642, features: 8, simplify: "20%" },
  "/data/administrative-boundaries/rose-hall-constituencies.geojson": { bytes: 2500, features: 7, simplify: "20%" },
  "/data/demographics/georgetown-census-districts.geojson": { bytes: 29518, features: 63, simplify: "20%" },
  "/data/demographics/guyana-admin-regions-population.geojson": { bytes: 72721, features: 10, simplify: "20%" },
  "/data/demographics/linden-census-districts.geojson": { bytes: 35659, features: 31, simplify: "20%" },
  "/data/demographics/new-amsterdam-census-districts.geojson": { bytes: 6667, features: 12, simplify: "20%" },
  "/data/planning-and-development/silica-city-boundary.geojson": { bytes: 1444, features: 3, simplify: "20%" },
};
